FROM node:18-alpine

ENV NODE_ENV=development
ENV APP_DIR=/var/app/auth-boilerplate

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN apk add --no-cache python3 g++ make

# Add a global package
RUN pnpm add -g @upleveled/preflight@latest

WORKDIR ${APP_DIR}

ENTRYPOINT ["/bin/sh", "./scripts/run_service.dev.sh"]