FROM node:18-alpine

ENV NODE_ENV=development
ENV APP_DIR=/var/app/auth-boilerplate

# Ref: https://github.com/pnpm/pnpm/issues/784#issuecomment-1518582235
RUN corepack enable && corepack prepare pnpm@latest --activate

# Enable `pnpm add --global` on Alpine Linux by setting
# home location environment variable to a location already in $PATH
# https://github.com/pnpm/pnpm/issues/784#issuecomment-1518582235
ENV PNPM_HOME=/usr/local/bin

# Add a global package
RUN pnpm add --global @upleveled/preflight@latest

WORKDIR ${APP_DIR}

ENTRYPOINT ["/bin/sh", "./scripts/run_service.dev.sh"]